In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
## One hot representation
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[9086, 5133, 5706, 6457],
 [9086, 5133, 5706, 3118],
 [9086, 7057, 5706, 1726],
 [6471, 8807, 3578, 6000, 9163],
 [6471, 8807, 3578, 6000, 7830],
 [7116, 9086, 7484, 5706, 1906],
 [1188, 5571, 4758, 6000]]

In [5]:
# Word embedding reprsentation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [6]:
sent_length = 8

In [7]:
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 9086, 5133, 5706, 6457],
       [   0,    0,    0,    0, 9086, 5133, 5706, 3118],
       [   0,    0,    0,    0, 9086, 7057, 5706, 1726],
       [   0,    0,    0, 6471, 8807, 3578, 6000, 9163],
       [   0,    0,    0, 6471, 8807, 3578, 6000, 7830],
       [   0,    0,    0, 7116, 9086, 7484, 5706, 1906],
       [   0,    0,    0,    0, 1188, 5571, 4758, 6000]], dtype=int32)

In [8]:
## Feature representation
dim=10

In [17]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim))
model.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [18]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


array([[[-2.72571202e-02,  4.85106967e-02, -2.87403110e-02,
         -4.19310331e-02,  9.80471447e-03, -3.30792554e-02,
         -2.69785654e-02, -2.57086400e-02, -6.27368689e-03,
         -1.96750294e-02],
        [-2.72571202e-02,  4.85106967e-02, -2.87403110e-02,
         -4.19310331e-02,  9.80471447e-03, -3.30792554e-02,
         -2.69785654e-02, -2.57086400e-02, -6.27368689e-03,
         -1.96750294e-02],
        [-2.72571202e-02,  4.85106967e-02, -2.87403110e-02,
         -4.19310331e-02,  9.80471447e-03, -3.30792554e-02,
         -2.69785654e-02, -2.57086400e-02, -6.27368689e-03,
         -1.96750294e-02],
        [-2.72571202e-02,  4.85106967e-02, -2.87403110e-02,
         -4.19310331e-02,  9.80471447e-03, -3.30792554e-02,
         -2.69785654e-02, -2.57086400e-02, -6.27368689e-03,
         -1.96750294e-02],
        [ 7.32010603e-03,  3.89742292e-02,  1.87095255e-03,
          4.10064571e-02,  2.53702290e-02,  3.09486873e-02,
         -8.35715607e-03, -4.77094054e-02,  4.760097

In [48]:
model.predict(the)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[[-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [ 0.00732011,  0.03897423,  0.00187095,  0.04100646,
          0.02537023,  0.03094869, -0.00835716, -0.04770941,
          0.04760097, -0.04248036],
        [ 0.03947959, -0.01392521, -0.01615607, -0.04693279,
          0.03333727, -0.03511281, -0.03135769,  0.01941481,
          0.0315495 ,  0.03820088],
        [-0.03823293,  0.02956888,  0.02244291,  0.0

In [46]:
the = np.array([[0, 0, 0, 0, 9086, 5133, 5706, 6457]])

In [47]:
the

array([[   0,    0,    0,    0, 9086, 5133, 5706, 6457]])

In [50]:
model.predict(the)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


array([[[-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [ 0.00732011,  0.03897423,  0.00187095,  0.04100646,
          0.02537023,  0.03094869, -0.00835716, -0.04770941,
          0.04760097, -0.04248036],
        [ 0.03947959, -0.01392521, -0.01615607, -0.04693279,
          0.03333727, -0.03511281, -0.03135769,  0.01941481,
          0.0315495 ,  0.03820088],
        [-0.03823293,  0.02956888,  0.02244291,  0.0

In [55]:
doc1=embedded_docs[[0]]
doc1

array([[   0,    0,    0,    0, 9086, 5133, 5706, 6457]], dtype=int32)

In [56]:
model.predict(doc1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[[-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [ 0.00732011,  0.03897423,  0.00187095,  0.04100646,
          0.02537023,  0.03094869, -0.00835716, -0.04770941,
          0.04760097, -0.04248036],
        [ 0.03947959, -0.01392521, -0.01615607, -0.04693279,
          0.03333727, -0.03511281, -0.03135769,  0.01941481,
          0.0315495 ,  0.03820088],
        [-0.03823293,  0.02956888,  0.02244291,  0.0

In [58]:
test = model.predict(embedded_docs[[0]])
test

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[[-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [-0.02725712,  0.0485107 , -0.02874031, -0.04193103,
          0.00980471, -0.03307926, -0.02697857, -0.02570864,
         -0.00627369, -0.01967503],
        [ 0.00732011,  0.03897423,  0.00187095,  0.04100646,
          0.02537023,  0.03094869, -0.00835716, -0.04770941,
          0.04760097, -0.04248036],
        [ 0.03947959, -0.01392521, -0.01615607, -0.04693279,
          0.03333727, -0.03511281, -0.03135769,  0.01941481,
          0.0315495 ,  0.03820088],
        [-0.03823293,  0.02956888,  0.02244291,  0.0

In [59]:
test.shape

(1, 8, 10)